image: debian/stable

secrets:
  - 847f7bd1-cee2-48a9-93d9-8ebef49c6984

sources:
  - https://git.sr.ht/~cypheon/Idris2#rapid
  - git@git.sr.ht:~cypheon/rapid

repositories:
  llvm-10: http://apt.llvm.org/buster/ llvm-toolchain-buster-10 main 15CF4D18AF4F7421

packages:
  - chezscheme
  - cmake
  - libgmp-dev
  - ninja-build
  - python3-pip
  # From LLVM-10 repository:
  - clang-10
  - llvm-10-dev

environment:
  PATH: /home/build/.idris2/bin:/usr/lib/llvm-10/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

tasks:
  - install-prerequisites: |
      sudo pip3 install setuptools wheel
      sudo pip3 install lit

  - load-prebuilt-idris2: |
      cd Idris2
      idris2_commit=$(git show-ref --hash --head refs/HEAD)
      curl -LsSf -o /tmp/idris2_prebuilt.tar.gz "https://neo.sinyax.net/cdn/artifacts/idris2_debian_${idris2_commit}.tar.gz"
      cd $HOME
      tar xzvf /tmp/idris2_prebuilt.tar.gz
      idris2 --version

  - build: |
      cd rapid
      git submodule update --init --recursive

      make -C external/llvm-statepoint-utils dist/llvm-statepoint-tablegen.h unified
      cmake -G Ninja .
      ninja

  - test: |
      cd rapid
      ninja test

triggers:
  - action: email
    condition: failure
    to: Johann Rudloff <johann+builds.sr.ht@sinyax.net>
