image: freebsd/latest

sources:
  - https://git.sr.ht/~cypheon/rapid

packages:
  - boehm-gc
  - cmake
  - coreutils
  - gmake
  - gmp
  - llvm11
  - ninja
  - py38-pip

environment:
  PATH: /home/build/.idris2/bin:/usr/home/build/.local/bin/:/usr/local/llvm11/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
  CHEZ: /usr/local/bin/chez-scheme

tasks:
  - install-chezscheme: |
      # Threaded Chez Scheme Runtime
      curl -LsSf -o /tmp/chez.txz https://sinyax.net/chez-scheme-9.5.2.txz
      sudo /usr/sbin/pkg install -yf /tmp/chez.txz

      # Install `sha256sum` script:
      printf -- '#\!/bin/sh\nexec shasum -a 256 "$@"\n' | sudo tee /usr/local/bin/sha256sum
      sudo chmod 755 /usr/local/bin/sha256sum

  - install-lit: |
      pip install lit
      lit --version

  - load-prebuilt-idris2: |
      idris2_commit=$(git ls-remote 'https://git.sr.ht/~cypheon/Idris2' refs/heads/rapid | awk '{print $1}')
      curl -LsSf -o /tmp/idris2_prebuilt.tar.gz "https://neo.sinyax.net/cdn/artifacts/idris2_freebsd_${idris2_commit}.tar.gz"
      cd $HOME
      tar xzvf /tmp/idris2_prebuilt.tar.gz
      idris2 --version

  - add-swap: |
      sudo dd if=/dev/zero of=/usr/swap0 bs=1m count=0 seek=4096
      sudo chmod 0600 /usr/swap0
      echo 'md99	none	swap	sw,file=/usr/swap0,late	0	0' | sudo tee -a /etc/fstab
      sudo /sbin/swapon -aL

  - build: |
      cd $(grealpath rapid)
      git submodule update --init --recursive

      gmake -C external/llvm-statepoint-utils dist/llvm-statepoint-tablegen.h unified

      cmake -G Ninja .
      ninja

  - test: |
      cd $(grealpath rapid)
      ninja test

triggers:
  - action: email
    condition: failure
    to: Johann Rudloff <johann+builds.sr.ht@sinyax.net>
